[ftpconfig]
port=2121
maxusers=10
interface=0.0.0.0
external_ip=127.0.0.1
local_mask=255.255.255.0
minport=40000
maxport=40100
logfilepath=/work/tests/fftplog
follow_symlinks=0

[anonymous]
pswd=*
accs=readonly
root=/work/tests/ftpshare

[uploader]
pswd=Weakuploaderpassword111
accs=upload
root=/work/tests/ftpshare

[webadmin]
pswd=VeryStrongadminpassword222
accs=admin
root=/work/tests/ftpshare
