[ftpconfig]
port=2121
maxusers=10
interface=0.0.0.0
external_ip=127.0.0.1
local_mask=255.255.255.0
minport=41000
maxport=41100
logfilepath=/tmp/server_tmpfs.log
follow_symlinks=0

[anonymous]
pswd=*
accs=readonly
root=/tmp/tinyfs/ftpshare

[uploader]
pswd=Weakuploaderpassword111
accs=upload
root=/tmp/tinyfs/ftpshare
